---
apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      args:
        [
          "--context=git://github.com/YmirKhang/kaniko-demo",
          "--destination=gcr.io/mx-labs-k8s-intro/labs_k8s_intro_mlflow_server:1.0.0",
        ]
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
